### ISSUE TITLE
Make cat_for_status(), dog_for_status() generic

### ISSUE THREAD

**Issue by richierocks** [sckott/httpcode#5]
Currently, to incorporate these functions into an `httr` workflow, I have to do

```r
res <- httr::GET("some url")
cat_for_status(status_code(res))
```

It would be useful to be able to write

```r
res <- httr::GET("some url")
cat_for_status(res)
```

To achieve this, `cat_for_status()` needs to be made into an S3 generic, with methods for `integer` and `response` classes. Likewise for `dog_for_status()`.

**Comment by sckott** [comment]
@richierocks  any thoughts?
