### ISSUE TITLE
Add additional http codes not in the RFC's

### ISSUE THREAD

**Issue by sckott** [sckott/httpcode#6]
Recently saw 520 code for the first time, via https://github.com/ropenscilabs/citecorp/issues/5 

There's lots of custom codes https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Unofficial_codes 

Probably good to add these if people may run into them

**Comment by Selbosh** [comment]
+1 for this. I keep hitting error codes 520 and 521 when using **citecorp**. I think these errors come from CloudFlare. Having to roll my own try-catch for the timebeing.

**Comment by sckott** [comment]
thanks for the +1 - i'll bump this higher in the priority list

**Comment by Bisaloo** [comment]
Got a 524 with citecorp as well.

According to [cloudflare help](https://community.cloudflare.com/t/community-tip-fixing-error-524-a-timeout-occurred/42342), it signals a time out.

**Comment by sckott** [comment]
thanks @Bisaloo  for the note. i'll add that too

**Comment by sckott** [comment]
done now, making associated updates to `fauxpas`, then `citecorp`

**Comment by sckott** [comment]
need to get new version of httpcode and fauxpas to CRAN first, so new version of citecorp on CRAN hopefully mid next week
